### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0

### ISSUE THREAD

**Issue by devshiro** [lucacampanella/corda-flows-doc-builder#16]
Hi!

An issue emerged from the cd project, in 2 different MRs, both failed to run the jarAnalyzerTask with the exception mentioned in the title and with a stacktrace:
`
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0
	at spoon.support.util.EmptyClearableList.get(EmptyClearableList.java:79)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.addToMapIfNoException(MethodInvocation.java:149)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:108)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.StaticAnalyzerUtils.getAllRelevantMethodInvocations(StaticAnalyzerUtils.java:376)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.StaticAnalyzerUtils.getAllRelevantMethodInvocations(StaticAnalyzerUtils.java:385)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.CodeFlowBreak.fromStatement(CodeFlowBreak.java:47)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.instantiateStatement(MatcherHelper.java:291)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.fromCtStatementsToStatements(MatcherHelper.java:306)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:134)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:68)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:68)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:68)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:68)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.MethodInvocation.fromCtStatement(MethodInvocation.java:68)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.StaticAnalyzerUtils.getAllRelevantMethodInvocations(StaticAnalyzerUtils.java:376)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.StaticAnalyzerUtils.getAllRelevantMethodInvocations(StaticAnalyzerUtils.java:385)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.StaticAnalyzerUtils.getAllRelevantMethodInvocations(StaticAnalyzerUtils.java:385)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.SubFlowBuilder.fromCtStatement(SubFlowBuilder.java:106)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.initiateIfCordaRelevantStatement(MatcherHelper.java:234)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.instantiateStatement(MatcherHelper.java:282)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.fromCtStatementsToStatements(MatcherHelper.java:306)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.AnalyzerWithModel.analyzeFlowLogicClass(AnalyzerWithModel.java:89)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.SubFlowBuilder.fromCtStatement(SubFlowBuilder.java:173)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.initiateIfCordaRelevantStatement(MatcherHelper.java:234)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.instantiateStatement(MatcherHelper.java:282)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.fromCtStatementsToStatements(MatcherHelper.java:306)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.AnalyzerWithModel.analyzeFlowLogicClass(AnalyzerWithModel.java:89)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.instructions.SubFlowBuilder.fromCtStatement(SubFlowBuilder.java:173)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.initiateIfCordaRelevantStatement(MatcherHelper.java:234)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.instantiateStatement(MatcherHelper.java:282)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.matchers.MatcherHelper.fromCtStatementsToStatements(MatcherHelper.java:306)
	at com.github.lucacampanella.callgraphflows.staticanalyzer.AnalyzerWithModel.analyzeFlowLogicClass(AnalyzerWithModel.java:89)
	at com.github.lucacampanella.callgraphflows.DrawerUtil.drawFromClass(DrawerUtil.java:59)
	at com.github.lucacampanella.callgraphflows.DrawerUtil.drawAllStartableClasses(DrawerUtil.java:46)
	at com.github.lucacampanella.callgraphflows.Main.call(Main.java:83)
	at com.github.lucacampanella.callgraphflows.Main.main(Main.java:58)
`

Please if you have any ideas what could caused this, help us out.

Best regards
Mark

**Comment by lucacampanella** [comment]
Hi, it seems here the arguments of the invocation (`inv.getArguments()`) and the parameters of its declaration (`inv.getExecutable().getDeclaration().getParameters()`) don't match. This can be an error from spoon or can be a problem related to not being able to access the declaration because it's not in the source path of spoon. If you want to further debug I suggest looking with the debugger at the fields of the two objects I highlighted before. 
Adding the exception to the catch seems reasonable, also because the code is there in order to support the feature that keeps track of many opened sessions at the same time. Since this feature is not implemented yet, this part of the code could also be left out (all the body of `for(int i = 0; i < arguments.size(); ++i) {`).
Thanks
